### ISSUE TITLE
Error on compiling package

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/auv8_mission_controller_behaviors#10]
## Expected Behavior
The catking_make action should complete without error

## Current Behavior
catkin_make action fails

See pastebin : https://pastebin.com/bvVBbA41

## Possible Solution
https://answers.ros.org/question/288967/build-package-with-system_lib-not-found/

## Comments
N/A

## Environment Used
Local computer

**Comment by alexemdesgagne** [comment]
This is an old repo replaced by sonia-behaviors https://github.com/sonia-auv/sonia-behaviors.
